### ISSUE TITLE
CND does not use KUBECONFIG variable

### ISSUE THREAD

**Issue by paurosello** [cloudnativedevelopment/cnd#149]
**Describe the bug**
CND does not use the KUBECONFIG environemnt variable and always looks in the user's home folder for the configuration

**To Reproduce**
```
export KUBECONFIG=/home/pau/Desktop/cndtest/test.config
cnd up
    Activating your cloud native development environment...
    Error: stat /home/pau/.kube/config: no such file or directory
```

**Expected behavior**
CDN should read from the environment variable first

**Desktop (please complete the following information):**
 - OS: Ubuntu, Mac OS
 - All versions?

**Comment by rberrelleza** [comment]
Makes sense, I think cnd should just follow the same pattern that kubectl. What do you think of also having a --kubeconfig parameter?
