### ISSUE TITLE
Mention cluster and namespace on errors

### ISSUE THREAD

**Issue by rberrelleza** [cloudnativedevelopment/cnd#155]
**Is your feature request related to a problem? Please describe.**
When okteto can't find a deployment, it's not very clear which context it was used:
```console
➜  okteto up                        
Activating your cloud native development environment...
Error: deployments.apps "website" not found
```

**Describe the solution you'd like**
It would be useful if the error message included the namespace and cluster / context name it used

This is related to #149

**Comment by pchico83** [comment]
It could be interesting to show the kubeconfig path used too.
